/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lampralexandros@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Uprofile model module.
 * @module model/Uprofile
 * @version 1.0.0
 */
class Uprofile {
    /**
     * Constructs a new <code>Uprofile</code>.
     * @alias module:model/Uprofile
     * @param uemail {String} 
     * @param upassword {String} 
     * @param uname {String} 
     * @param ulastname {String} 
     * @param umale {String} 
     * @param uadress {String} 
     * @param udate {Date} 
     * @param uphone {Number} 
     */
    constructor(uemail, upassword, uname, ulastname, umale, uadress, udate, uphone) { 
        
        Uprofile.initialize(this, uemail, upassword, uname, ulastname, umale, uadress, udate, uphone);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, uemail, upassword, uname, ulastname, umale, uadress, udate, uphone) { 
        obj['uemail'] = uemail;
        obj['upassword'] = upassword;
        obj['uname'] = uname;
        obj['ulastname'] = ulastname;
        obj['umale'] = umale;
        obj['uadress'] = uadress;
        obj['udate'] = udate;
        obj['uphone'] = uphone;
    }

    /**
     * Constructs a <code>Uprofile</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Uprofile} obj Optional instance to populate.
     * @return {module:model/Uprofile} The populated <code>Uprofile</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Uprofile();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('uemail')) {
                obj['uemail'] = ApiClient.convertToType(data['uemail'], 'String');
            }
            if (data.hasOwnProperty('upassword')) {
                obj['upassword'] = ApiClient.convertToType(data['upassword'], 'String');
            }
            if (data.hasOwnProperty('uname')) {
                obj['uname'] = ApiClient.convertToType(data['uname'], 'String');
            }
            if (data.hasOwnProperty('ulastname')) {
                obj['ulastname'] = ApiClient.convertToType(data['ulastname'], 'String');
            }
            if (data.hasOwnProperty('umale')) {
                obj['umale'] = ApiClient.convertToType(data['umale'], 'String');
            }
            if (data.hasOwnProperty('uadress')) {
                obj['uadress'] = ApiClient.convertToType(data['uadress'], 'String');
            }
            if (data.hasOwnProperty('udate')) {
                obj['udate'] = ApiClient.convertToType(data['udate'], 'Date');
            }
            if (data.hasOwnProperty('uphone')) {
                obj['uphone'] = ApiClient.convertToType(data['uphone'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
Uprofile.prototype['_id'] = undefined;

/**
 * @member {String} uemail
 */
Uprofile.prototype['uemail'] = undefined;

/**
 * @member {String} upassword
 */
Uprofile.prototype['upassword'] = undefined;

/**
 * @member {String} uname
 */
Uprofile.prototype['uname'] = undefined;

/**
 * @member {String} ulastname
 */
Uprofile.prototype['ulastname'] = undefined;

/**
 * @member {String} umale
 */
Uprofile.prototype['umale'] = undefined;

/**
 * @member {String} uadress
 */
Uprofile.prototype['uadress'] = undefined;

/**
 * @member {Date} udate
 */
Uprofile.prototype['udate'] = undefined;

/**
 * @member {Number} uphone
 */
Uprofile.prototype['uphone'] = undefined;






export default Uprofile;

