/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lampralexandros@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TempApi);
  }
}(this, function(expect, TempApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TempApi.Uprofile();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Uprofile', function() {
    it('should create an instance of Uprofile', function() {
      // uncomment below and update the code to test Uprofile
      //var instane = new TempApi.Uprofile();
      //expect(instance).to.be.a(TempApi.Uprofile);
    });

    it('should have the property id (base name: "_id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new TempApi.Uprofile();
      //expect(instance).to.be();
    });

    it('should have the property uemail (base name: "uemail")', function() {
      // uncomment below and update the code to test the property uemail
      //var instance = new TempApi.Uprofile();
      //expect(instance).to.be();
    });

    it('should have the property upassword (base name: "upassword")', function() {
      // uncomment below and update the code to test the property upassword
      //var instance = new TempApi.Uprofile();
      //expect(instance).to.be();
    });

    it('should have the property uname (base name: "uname")', function() {
      // uncomment below and update the code to test the property uname
      //var instance = new TempApi.Uprofile();
      //expect(instance).to.be();
    });

    it('should have the property ulastname (base name: "ulastname")', function() {
      // uncomment below and update the code to test the property ulastname
      //var instance = new TempApi.Uprofile();
      //expect(instance).to.be();
    });

    it('should have the property umale (base name: "umale")', function() {
      // uncomment below and update the code to test the property umale
      //var instance = new TempApi.Uprofile();
      //expect(instance).to.be();
    });

    it('should have the property uadress (base name: "uadress")', function() {
      // uncomment below and update the code to test the property uadress
      //var instance = new TempApi.Uprofile();
      //expect(instance).to.be();
    });

    it('should have the property udate (base name: "udate")', function() {
      // uncomment below and update the code to test the property udate
      //var instance = new TempApi.Uprofile();
      //expect(instance).to.be();
    });

    it('should have the property uphone (base name: "uphone")', function() {
      // uncomment below and update the code to test the property uphone
      //var instance = new TempApi.Uprofile();
      //expect(instance).to.be();
    });

  });

}));
